const ENV = process.env;

const ADMIN_NAME = ENV.ADMIN_NAME;
const ADMIN_PASSWORD = ENV.ADMIN_PASSWORD;

const MAILGUN_API_KEY = ENV.MAILGUN_API_KEY;
const MAILGUN_DOMAIN = ENV.MAILGUN_DOMAIN;

const MANDRILL_API_KEY = ENV.MANDRILL_API_KEY;

const PRIMARY_EMAIL_BACKEND = ENV.PRIMARY_EMAIL_BACKEND;

const DEVELOPMENT = ENV.DEVELOPMENT === 'true';

const PORT = ENV.PORT;

module.exports = {
  ADMIN_NAME,
  ADMIN_PASSWORD,
  MAILGUN_API_KEY,
  MAILGUN_DOMAIN,
  MANDRILL_API_KEY,
  PRIMARY_EMAIL_BACKEND,
  DEVELOPMENT,
  PORT
};
